name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        anyway_config: ["~> 2.0"]
        include:
        - ruby: "2.6"
          anyway_config: "~> 2.0"
        - ruby: "3.0"
          anyway_config: "~> 2.0"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      env:
        ANYWAY_CONFIG_VERSION: ${{ matrix.anyway_config }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.15
        bundler-cache: true
    - name: Run RSpec
      run: |
        bundle exec rspec
    - name: Run RSpec w/o gRPC
      env:
        GRPC: false
      run: |
        bundle exec rspec
